logger:
    version: 1
    formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simple 
            level: INFO
    root:
        level: INFO
        handlers: [console]

IGPreprocessor:
    max_caption_char_length: 140
    language: "en"
    vocabulary_size: 10000
    embedding_dimensionality: 300
    raw_data_path: "./.cache/data/instagram/ig_sample.tar.gz"
    raw_data_url: "https://tweakstory.stefanmesken.info/data/ig_sample.tar.gz"
    raw_data_directory: "ig_sample"
    raw_data_group_names:
        insta-caption-train.json: "train"
        insta-caption-test1.json: "eval"
        insta-caption-test2.json: "test"
    ResnetEncoder: !include resnet_encoder.yaml
    image_transformations: !include image_transformations.yaml
    batch_size: 32
    device_name: "cpu"

Trainer:
    pad_token_id: 0
    unk_token_id: 0
    batch_size: 16
    max_epochs: 100
    device_name: "cpu"
    dataloader_num_workers: 4

    IGDataset:
        cache_location: "./.cache/data/instagram/"
        dataset_name: "ig_sample"
        split: "train"
        image_transformations: !include image_transformations.yaml

    ShowAttendTell:
        ResnetEncoder: !include resnet_encoder.yaml
        AttentionLSTMDecoder: !include attention_lstm_decoder.yaml
